#!/bin/bash
#chkconfig: 35 99 99
# description: stor_redfishserver
# MPD, 11/9/2003'
### BEGIN INIT INFO 
# Provides: stor_redfishserver
# Required-Start:   $local_fs $network $ALL
# X-UnitedLinux-Should-Start:
# Required-Stop:    $local_fs $network
# X-UnitedLinux-Should-Stop:'
# Default-Start:    2 3 4 5 6
# Default-Stop:     0 1 6
# Short-Description: Storage Management Redfish Service 
# Description:      Storage Management Redfish Service
### END INIT INFO
                                                                
GREEN_COLOR='\033[92m'
RED_COLOUR='\033[91m'
RESET_COLOUR='\033[0m'

REDFISHSERVER_NAME="maxView Storage Manager Redfish Server" 
NODE=node
REDFISHSERVER_PATH=/usr/StorMan/RedfishServer

return_status() {
     processid=`ps -eaf | grep MSCC | grep -v "grep" | awk '{print $2}'`
     if [ ! -z "$processid" ] ; then
         return 0
     else
         return 3
     fi
 }

start() {
    return_status
    RETVAL=$?
    if [ $RETVAL -eq 0 ] ; then
	echo "$REDFISHSERVER_NAME is already running"
	exit 0
    fi
	   
    [ -x $REDFISHSERVER_PATH/$NODE ] || exit 5
    echo -n $"Starting $REDFISHSERVER_NAME "
    ($REDFISHSERVER_PATH/$NODE $REDFISHSERVER_PATH/MSCCRestfulServer.js &) > /var/log/daemon/maxviewredfishserver.out.log 2> /var/log/daemon/maxviewredfishserver.err.log
     sleep 5
     return_status
     RETVAL=$?
     if [ $RETVAL -eq 0 ] ; then
         echo -e "[ ${GREEN_COLOR}OK${RESET_COLOUR} ]"	   
     else
         echo -e "[ ${RED_COLOR}FAILED${RESET_COLOUR} ]"	   
     fi
     return $RETVAL
}

                                                                
stop() {

   [ -x $REDFISHSERVER_PATH/$node ] || exit 5
    echo -n $"Stopping $REDFISHSERVER_NAME "
    kill -9 `ps -eaf | grep MSCC | grep -v "grep" | awk '{print $2}'` 2>/dev/null 
    sleep 5
    echo -e "[ ${GREEN_COLOR}OK${RESET_COLOUR} ]"
}
                                                                
case "$1" in
  start)
      start
  ;;
  stop)
      stop
  ;;
  status)
    return_status
    RETVAL=$?
    if [ $RETVAL -ne 0 ] ; then
        echo "$REDFISHSERVER_NAME is NOT running"
    else
        echo "$REDFISHSERVER_NAME is running"
    fi
    ;;
  restart|reload)
      stop
      start
  ;;
  *)
      echo $"Usage: $0 {start|stop|restart|status}"
      exit 1
  esac
exit 0
